### ISSUE TITLE
Problem: Travis builds are not using hydra.fractalide.com as substituter

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide-infra#1]
Resources:

 - https://unix.stackexchange.com/questions/295947/local-nix-cache-is-ignored-because-nar-info-file-lacks-a-signature#309963
 - NixOS/nixpkgs#35509

**Comment by clacke** [comment]
I have this locally (`/etc/nix/nix.cfg`):

```
substituters = https://cache.nixos.org/ https://hydra.fractalide.com
trusted-substituters = https://cache.nixos.org/ https://hydra.fractalide.com
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.fractalide.com-1:EnGZBrRHPabgRET+umo2e+wNrw+c4QdbsxsnV5H7zs0=
```

And this on `hydra` (`configuration.nix`):

```
  services = {
    openssh.enable = true;
    nix-serve = {
      enable = true;
      secretKeyFile = "/etc/nixos/secret/nix-serve/hydra.fractalide.com-1";
    };
  };
```

But I get:

```
these paths will be fetched (0.00 MiB download, 4.23 MiB unpacked):
  /nix/store/hk6gfh9ryibk4a4nhk541ga4wj07jx47-typed-racket-more-env
  /nix/store/wzgr69i39bv4cdcb7jdydnijzhr8nvmj-typed-racket-more
warning: substituter 'https://hydra.fractalide.com' does not have a valid signature for path '/nix/store/wzgr69i39bv4cdcb7jdydnijzhr8nvmj-typed-racket-more'
warning: substituter 'https://hydra.fractalide.com' does not have a valid signature for path '/nix/store/hk6gfh9ryibk4a4nhk541ga4wj07jx47-typed-racket-more-env'
cannot build derivation '/nix/store/16zmb8l7zx4qdya4zaqqfd0yw42gpa5p-292967d3l8hy9ssdfvdyq18ihykmpl5f-fractalide.drv': 1 dependencies couldn't be built
```

**Comment by clacke** [comment]
@sjmackenzie Do you think Joachim and friends might have ideas on how to proceed?

I'm going to check freenode #nixos.

**Comment by sjmackenzie** [comment]
@qknight do you or @aszlig have any idea about this?

**Comment by clacke** [comment]
Hmmm ok, nix-serve is actually hosting on :5000. So I'm getting the package from hydra, which doesn't have the key. Maybe I can skip nix-serve and just feed hydra the key. That's probably the normal way to do it when you have a hydra.

**Comment by clacke** [comment]
> **secret-key-files**

>    A whitespace-separated list of files containing secret (private) keys. These are used to sign locally-built paths. They can be generated using nix-store --generate-binary-cache-key. The corresponding public key can be distributed to other users, who can add it to trusted-public-keys in their nix.conf.

There we go.

https://nixos.org/nix/manual/#ch-files

**Comment by clacke** [comment]
Now the question is how to make Nix regenerate the derivations it already built.

**Comment by sjmackenzie** [comment]
oh probably whacking the /var/hydra/somewhere/in/there dir will make hydra rebuild it all. IIRC

**Comment by clacke** [comment]
nix sign-paths --all

According to my savior in #nixos.

**Comment by clacke** [comment]
Well. That went ridiculously fast. I wonder if it signed anything at all.

**Comment by sjmackenzie** [comment]
huzzah!

**Comment by clacke** [comment]
No huzzah yet. Paths are still unsigned. :-(

**Comment by sjmackenzie** [comment]
try deleting `/var/lib/hydra/scm/git/*` and see what happens.

**Comment by clacke** [comment]
Nah that's just git repos.

**Comment by clacke** [comment]
`/nix/var/nix/gcroots/hydra`

bingo

**Comment by clacke** [comment]
Oh wait now I got what you meant. Deleting git caches as well.

**Comment by clacke** [comment]
Sigh. I will solve an issue with racket2nix and then propagate that change instead. :-)

**Comment by sjmackenzie** [comment]
haha that's probably the simplest approach yes :-) no doubt there will be one little dependency that doesn't change and breaks the lot!

**Comment by clacke** [comment]
So, the thing was I was trying to invalidate my local caches to verify that things had worked, but I hunted down every cache I could find and it still complained "[I got this unsigned archive from hydra.fractalide..]" even when I knew I had deleted the path on hydra. :-)

So now I'm just trying to make this work directly on Travis instead.

**Comment by aszlig** [comment]
If you use local store serving from Hydra itself (which I imply from the error messages posted above), you currently have to use the (deprecated) `binary_cache_secret_key_file` Hydra option to add a `Sig` header to your `narinfo`.

**Comment by clacke** [comment]
I'm not entirely sure. NixOS/hydra#435 seems to be talking about some special mode. What hydra is doing currently is simply serving from /nix/store I guess.

But I'll add the parameters from the linked issue and see what happens.

**Comment by aszlig** [comment]
[This](https://github.com/NixOS/hydra/blob/7f6d52f4c3b7587a34c85971a6c32c068f021316/src/lib/Hydra/View/NARInfo.pm) is the current source code for generating the `narinfo` and if you don't serve the store via other means (which implies that you need to override the URLs relevant for substitution using for example proxy) using `binary_cache_secret_key_file` is the only way to serve the signature right now without patching Hydra.

**Comment by clacke** [comment]
Ok cool, then I'll trim the config down to just that. Thanks!

**Comment by aszlig** [comment]
@clacke: Setting `store_uri` is fine in addition to that as well, because that's what the new queue runner uses.

**Comment by clacke** [comment]
Hm, that gave me `warning: 'https://hydra.fractalide.com' does not appear to be a binary cache`.

And checking `curl https://hydra.fractalide.com/nix-cache-info` gives me a 404 page.

Reverting my revert.

**Comment by clacke** [comment]
There we go! That's progress. https://hydra.fractalide.com/73v3fvi03mw59avfdhf6jzqnbdlyzhpx.narinfo :

    Caught exception in Hydra::View::NARInfo->process "cannot open file '/etc/nixos/secret/nix-serve/hydra.fractalide.com-1': Permission denied at /nix/store/9i3nxb4bywn2fbl5y2a6wck014f6k1b8-hydra-perl-deps/lib/perl5/site_perl/5.24.3/x86_64-linux-thread-multi/Nix/Utils.pm line 37."

**Comment by clacke** [comment]
Success!
