### ISSUE TITLE
Problem: macos fails with NIX_SSL_CERT_FILE: unbound variable

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide-infra#2]
https://travis-ci.org/fractalide/fractalide/jobs/385683241

**Comment by clacke** [comment]
Yes. I notified Kozar et al at travis-ci/travis-ci#9682 .

**Comment by clacke** [comment]
> Upstream: NixOS/nix#2193

**Comment by sjmackenzie** [comment]
https://github.com/NixOS/nix/commit/6ba1726eeb58cd8e7d69e2a090346f26fdf634a5 should fix it.
