### ISSUE TITLE
Problem: https://hydra.fractalide.com/ is 502

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide-infra#5]
https://hydra.fractalide.com/

> 502 Bad Gateway

I've had a quick look, but I don't know what we changed.

**Comment by clacke** [comment]
@qknight @aszlig ?

**Comment by clacke** [comment]
Ok, `hydra-server.service` simply wasn't running. Odd.

**Comment by clacke** [comment]
```
-- Reboot --
Jul 25 07:53:01 mail.fractalide.com systemd[1]: Dependency failed for hydra-server.service.
Jul 25 07:53:01 mail.fractalide.com systemd[1]: hydra-server.service: Job hydra-server.service/start failed with result 'dependency'.
Jul 28 03:57:40 mail.fractalide.com systemd[1]: Started hydra-server.service.
```

Which dependency failed? Who knows.

**Comment by clacke** [comment]
Discovered now that `hydra-queue-runner` was also down:

```
-- Reboot --
Jul 25 07:53:01 mail.fractalide.com systemd[1]: Dependency failed for hydra-queue-runner.service.
Jul 25 07:53:01 mail.fractalide.com systemd[1]: hydra-queue-runner.service: Job hydra-queue-runner.service/start failed with result 'dependency'.
```

Started it manually.

**Comment by qknight** [comment]
when the disk gets very full, hydra might stop the build IIRC and maybe this caused the issue for you. call the GC occationally and `nix-store --optimize`

```
/dev/sda1   [===================-]   92%      3.2G     38.1G /
/dev/sda1   [===================-]   92%      3.2G     38.1G /nix/store
```

**Comment by clacke** [comment]
I will enable `auto-optimize-store` in `nix.conf` (through the appropriate `nix.*` attribute in `configuration.nix`). Is there really any drawback to that?

**Comment by clacke** [comment]
Now running `nix optimise-store`, which has nice curses feedback. :-)

**Comment by clacke** [comment]
Ah yes, `hydra-check-space` goes and kills `evaluator` and `queue-runner` if space is < 1 GiB and < 2 GiB, respectively.

And just now it went and killed the queue runner. But that's not why it didn't start up in the first place. But maybe it depended on something that checked space, and that's the mysterious dependency error?

**Comment by clacke** [comment]
Optimizing is only 30% done but already gained a few GiB. Restarting queue-runner.

**Comment by clacke** [comment]
```
# nix optimise-store
[28727 paths optimised, 9679.7 MiB / 1665771 inodes freed]
```

```
# grep -B 1 autoOpt /etc/nixos/configuration.nix 
  nix = {
    autoOptimiseStore = true;
```

```
# grep auto /etc/nix/nix.conf 
auto-optimise-store = true
```

**Comment by clacke** [comment]
Ok, so one drawback with `auto-optimise-store` is that the optimization spams the `hydra-queue-runner` log. I can live with that. Auto optimization is so much nicer than period optimization, especially in the case when disk is starting to run low, because with auto opt you don't get the swelling and trimming that you get with periodical.
